---
- name: This Playbook creates catalogue Service
  hosts: catalogue
  become: true
  tasks:
    - name: Disable Node.js module
      command: dnf module disable nodejs -y

    - name: Enable Node.js module version 18
      command: dnf module enable nodejs:18 -y

    - name: Installing Node-Js
      command: dnf install nodejs -y

    - name: RoboShop-User-Creation
      user:
        name: johnd
    
    - name: App Directory Creation      
      file:
        path: /app
        state: directory
    
    - name: Downloading catalogue.service
      get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: Unzipping catalogue.service
      unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes