---
- name: This Playbook create catalogue Service
  hosts: catalogue
  become: true
  tasks:
  - name: Disable Node.js module
      command: dnf module disable nodejs -y
      become: true

  - name: Enable Node.js module version 18
      command: dnf module enable nodejs:18 -y
      become: true 