---
- name: This Playbook For Mongo-Db Installation
  hosts: all
  become: true
  tasks:
    - name: Setup the MongoDB repo file
      copy:
        src: /home/centos/ansible-roboshop/mongo.repo
        dest: /etc/yum.repos.d/
        mode: 0644

    - name: Installing-Mongo-DB
      package:
        name: mongodb-org
        state: present
      notify: Start-MongoDB

    - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
      replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Restarted MongoDB Service 
      service:
        name: mongod
        state: restarted
      notify: Restart-MongoDB  

  handlers:  
    - name: Start-MongoDB 
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Restart-MongoDB 
      service:
        name: mongod
        state: restarted
