---
- name: THIS PLAY BOOK FOR USER DATA API SERVER
  hosts: users
  become: true
  tasks:
    - name: Install Node.js
      command: "{{item}}"
      loop:
        - dnf module disable nodejs -y
        - dnf module enable nodejs:18 -y
        - dnf install nodejs -y

    - name: Create Roboshop user
      user:
        name: roboshop

    - name: App directory creation
      file:
        path: /app
        state: directory

    - name: Downloading user data
      get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp

    - name: Unzip user.zip
      unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: Npm installation
      command: npm install
      args:
        chdir: /app

    - name: Copying user.SERVICE
      copy:
        src: /home/centos/ansible-roboshop/user.service
        dest: /etc/systemd/system/
      notify: ENABLE USER

    - name: Copying MONGO.REPO
      copy:
        src: /home/centos/ansible-roboshop/mongo.repo
        dest: /etc/yum.repos.d/

    - name: Installing MONGO SHELL
      dnf:
        name: mongodb-org-shell
        state: present

    # - name: Check if data exists in MongoDB
    #   command: "mongo --host mongodb.gonepudirobot.online --quiet --eval 'db.users.findOne({ name: \"user\" })'"
    #   ignore_errors: true
    #   register: existing_data_check

    - name: Load data into MongoDB if it doesn't exist
      command: mongo --host mongodb.gonepudirobot.online < /app/schema/user.js
      #when: existing_data_check.rc != 0

  handlers:
    - name: ENABLE USER
      command: "{{ item }}"
      loop:
        - systemctl daemon-reload
        - systemctl enable catalogue
        - systemctl start catalogue
